#!/usr/bin/env node
/**
 * Report Generator - Creates consolidated markdown report
 */

const fs = require('fs');
const path = require('path');

const [,, reportFolder, failedJobsPath, passedJobsPath, outputDir] = process.argv;

if (!reportFolder || !failedJobsPath || !passedJobsPath || !outputDir) {
  console.error('Usage: node report_generator.js <reportFolder> <failedJobsPath> <passedJobsPath> <outputDir>');
  process.exit(1);
}

const failedJobs = JSON.parse(fs.readFileSync(failedJobsPath, 'utf8'));
const passedJobs = JSON.parse(fs.readFileSync(passedJobsPath, 'utf8'));

const totalJobs = failedJobs.length + passedJobs.length;
const passRate = totalJobs > 0 ? ((passedJobs.length / totalJobs) * 100).toFixed(1) : 0;

const timestamp = new Date().toISOString().split('T')[0];

let report = `# Jenkins Daily QA Report - ${reportFolder}

**Generated:** ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Shanghai' })}  
**Build:** ${reportFolder}  
**Total Jobs:** ${totalJobs}  
**Pass Rate:** ${passRate}%  

---

## 📊 Executive Summary

| Status | Count | Percentage |
|--------|-------|------------|
| ✅ Passed | ${passedJobs.length} | ${passRate}% |
| ❌ Failed | ${failedJobs.length} | ${(100 - passRate).toFixed(1)}% |

---

## ✅ Passed Jobs (${passedJobs.length})

`;

if (passedJobs.length > 0) {
  passedJobs.forEach(job => {
    report += `- ${job.name} #${job.number}\n`;
  });
} else {
  report += `*No passed jobs*\n`;
}

report += `\n---\n\n## ❌ Failed Jobs (${failedJobs.length})\n\n`;

if (failedJobs.length > 0) {
  failedJobs.forEach(job => {
    report += `### ${job.name} #${job.number}\n\n`;
    
    const consoleLogPath = path.join(outputDir, `${job.name}_${job.number}_console.json`);
    if (fs.existsSync(consoleLogPath)) {
      try {
        const consoleData = JSON.parse(fs.readFileSync(consoleLogPath, 'utf8'));
        const consoleLog = consoleData.console || '';
        
        // Extract failure summary
        const failedTests = extractFailedTests(consoleLog);
        
        if (failedTests.length > 0) {
          report += `**Failed Tests:**\n`;
          failedTests.forEach(test => {
            report += `- ${test}\n`;
          });
        } else {
          report += `**Status:** Build failed (see console log)\n`;
        }
        
        report += `\n**Console Log (last 50 lines):**\n\`\`\`\n`;
        report += consoleLog.split('\n').slice(-50).join('\n');
        report += `\n\`\`\`\n\n`;
        
      } catch (error) {
        report += `*Error reading console log: ${error.message}*\n\n`;
      }
    } else {
      report += `*Console log not available*\n\n`;
    }
    
    report += `[View in Jenkins](http://tec-l-1081462.labs.microstrategy.com:8080/job/${job.name}/${job.number}/)\n\n`;
    report += `---\n\n`;
  });
} else {
  report += `*No failed jobs* 🎉\n`;
}

report += `\n---\n\n## 📝 Notes

- This report was automatically generated by the Jenkins QA Daily Agent
- For detailed analysis of failures, see individual job console logs
- Report saved to: \`${outputDir}\`

---

**End of Report**
`;

// Write report
const reportPath = path.join(outputDir, 'jenkins_daily_report.md');
fs.writeFileSync(reportPath, report, 'utf8');

console.log(`✓ Report generated: ${reportPath}`);

// Helper function to extract failed test names
function extractFailedTests(consoleLog) {
  const failedTests = [];
  const lines = consoleLog.split('\n');
  
  for (const line of lines) {
    // Pattern 1: WDIO test failures
    if (line.includes('FAILED') && line.includes('file://')) {
      const match = line.match(/FAILED in \w+ - (.*\.spec\.js)/);
      if (match) failedTests.push(match[1]);
    }
    
    // Pattern 2: Failed test cases
    if (line.match(/\[TC\d+\]/)) {
      const match = line.match(/\[(TC\d+[_\d]*)\]/);
      if (match) failedTests.push(match[1]);
    }
    
    // Pattern 3: Failed Summary
    if (line.startsWith('Failed test cases:')) {
      const testCases = line.replace('Failed test cases:', '').trim().split(',');
      failedTests.push(...testCases.map(tc => tc.trim()));
    }
  }
  
  return [...new Set(failedTests)]; // Remove duplicates
}
